version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_USERNAME}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    env_file:
      - .env
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
volumes:
  db-data:
